import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import fs from "fs";
import Post from "../components/Post";
import { getPostBySlug } from "../lib/api";
import { differenceInDays, parseISO } from "date-fns";
import profilePic from "../public/img/jeremy-profile@2x.png";

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jeremy Richardson&apos;s personal website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="hero">
        <div className="hero-container">
          <div className="hero-content">
            <h1 className="title">Hi, I&apos;m Jeremy Richardson</h1>
          </div>
          <div className="hero-image hero-section">
            <div className="profile-picture-border">
              <Image
                src={profilePic}
                width="200"
                height="200"
                className="profile-picture"
                alt="Jeremy Richardson"
              />
            </div>
          </div>
        </div>
      </div>
      <main className="main">
        <h2>Posts</h2>
        <article className="container prose prose-sm md:prose">
          {posts.map((post) => (
            <Post key={post.slug} post={post} />
          ))}
        </article>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getStaticProps() {
  const postFiles = fs.readdirSync("posts");

  const posts = postFiles
    .map((postFile) => {
      const slug = postFile.split(".")[0].slice(11);
      const post = getPostBySlug(slug);

      return { slug, ...post };
    })
    .filter((post) => post.frontmatter.published)
    .sort((a, b) => {
      const modifiedDays = differenceInDays(
        parseISO(b.modifiedDate),
        parseISO(a.modifiedDate)
      );
      const createDays = differenceInDays(
        parseISO(b.createDate),
        parseISO(a.createDate)
      );

      // first try and sort by modified date, otherwise sort by create date
      return modifiedDays || createDays;
    });

  return {
    props: {
      posts,
    },
  };
}
