import Head from "next/head";
import styles from "../styles/Home.module.css";
import fs from "fs";
import Post from "../components/Post";
import { getPostBySlug } from "../lib/api";
import { differenceInDays, parseISO } from "date-fns";
import { serialize } from "next-mdx-remote/serialize";
import rehypePrism from "rehype-prism-plus";
import remarkGfm from "remark-gfm";
import imageSize from "rehype-img-size";
import { ErrorBoundary } from "../components/ErrorBoundary";
import { isBefore } from "date-fns";
import { getPosts } from "../lib/wordpress";

import { SiteNav } from "../components/SiteNav";
import { Hero } from "../components/Hero";
import { About } from "../components/About";
import { Tech } from "../components/Tech";
import { WP_Post, WP_REST_API_Post, WP_REST_API_Posts } from "wp-types";

export default function Home({
  posts,
  wpPosts,
}: {
  posts: any;
  wpPosts: WP_REST_API_Posts;
}) {
  // const publishedPosts = posts.filter(
  //   (post:any) =>
  //     isBefore(new Date(post.createDate), new Date()) ||
  //     new Date(post.createDate) === new Date()
  // );
  const publishedPosts = wpPosts;
  console.log(Object.keys(publishedPosts));

  return (
    <ErrorBoundary>
      <Head>
        <title>Jeremy Richardson&apos;s personal website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.headerTest}>
        <SiteNav />
      </div>
      <div className={styles.container}>
        <Hero />

        <main className="main">
          <About />
          &nbsp;
          <Tech />
          &nbsp;
          <h2 id="posts">Posts</h2>
          <article className="container prose prose-sm md:prose">
            {publishedPosts.map((post) => (
              <Post key={post.id} post={post} />
            ))}
          </article>
        </main>

        <footer className={styles.footer}></footer>
      </div>
    </ErrorBoundary>
  );
}

export async function getStaticProps() {
  const wpPosts = await getPosts();
  console.log(wpPosts);

  const postFiles = fs.readdirSync("posts");

  const posts = await Promise.all(
    postFiles.map(async (postFile) => {
      const slug = postFile.split(".")[0].slice(11);
      const post = getPostBySlug(slug);

      const mdxSource = await serialize(post.frontmatter.description, {
        mdxOptions: {
          rehypePlugins: [rehypePrism, [imageSize, { dir: "public" }]],
          remarkPlugins: [remarkGfm],
        },
      });

      return {
        ...post,
        frontmatter: { ...post.frontmatter, description: mdxSource },
      };
    })
  ).then((posts) =>
    posts
      .filter((post) => post.frontmatter.published)
      .sort((a, b) => {
        const modifiedDays = differenceInDays(
          parseISO(b.modifiedDate),
          parseISO(a.modifiedDate)
        );
        const createDays = differenceInDays(
          parseISO(b.createDate),
          parseISO(a.createDate)
        );

        // first try and sort by modified date, otherwise sort by create date
        return modifiedDays || createDays;
      })
  );

  return {
    props: {
      wpPosts,
      posts,
    },
  };
}
