import Head from "next/head";
import styles from "../styles/Home.module.css";
import WpPost from "../components/WpPost";
import { ErrorBoundary } from "../components/ErrorBoundary";
import { getPosts } from "../lib/wordpress";

import { SiteNav } from "../components/SiteNav";
import { Hero } from "../components/Hero";
import { About } from "../components/About";
import { Tech } from "../components/Tech";
import { WP_REST_API_Posts } from "wp-types";

interface HomeProps {
  wpPosts: WP_REST_API_Posts;
}

export default function Home({ wpPosts }: HomeProps) {
  return (
    <ErrorBoundary>
      <Head>
        {/* eslint-disable-next-line react/no-unescaped-entities */}
        <title>Jeremy Richardson's personal website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.headerTest}>
        <SiteNav />
      </div>
      <div className={styles.container}>
        <Hero />

        <main className="main">
          <About />
          &nbsp;
          <Tech />
          &nbsp;
          <h2 id="posts">Posts</h2>
          <article className="container prose prose-sm md:prose">
            {wpPosts.map((post) => (
              <WpPost key={post.slug} post={post} />
            ))}
          </article>
        </main>

        <footer className={styles.footer}></footer>
      </div>
    </ErrorBoundary>
  );
}

export async function getStaticProps() {
  const wpPosts = await getPosts("publish", 99);

  return {
    props: {
      wpPosts,
    },
  };
}
